title: title
subtitle: A Portfolio Jekyll Theme Built for Developers
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "https://mr4ndr3w.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-sitemap
  - sass



defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


collections:
  authors:
    output: true


