title: mr4ndr3w@whoami:~$ _
subtitle: Have a nice time
description: whoami
author: 
  name: mr4ndr3w

url: "https://mr4ndr3w.github.io" 


theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-sitemap
  - sass

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# JEKYLL_ENV=production bundle exec jekyll serve



twitter_username:   mr4ndr3w
github_username:    mr4ndr3w
mastodon_username:  mr4ndr3w
keybase_username:   mr4ndr3w

baseurl:            ""
permalink:          /:year/:month/:day/:title:output_ext
excerpt_separator:  <!--cut-->
show_excerpts:      true
future:             true

header_pages:
  - tags.html
  - about.md

# Build settings
markdown:     kramdown
highlighter:  rouge


# Google Analytics
google_analytics:  G-XYJ076N3H2


# Page locations
tag_page:  /tags.html

